### ISSUE TITLE
Error on VS 2019 (v16.10) startup

### ISSUE THREAD

**Issue by MalcolmEllis** [cezarypiatek/MappingGeneratorIssueTracker#1]
SetSite failed for package [MappingGeneratorProPackage]Source: 
'PresentationFramework' Description: The 'ResourceAssembly' property of the 
'Application' type cannot be changed after it has been set. 
System.InvalidOperationException: The 'ResourceAssembly' property of the 
'Application' type cannot be changed after it has been set. at 
System.Windows.Application.set_ResourceAssembly(Assembly value) at 
MappingGeneratorPro.MappingGeneratorProPackage.&lt;InitializeAsync&gt;d__1.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- at 
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task 
task) at 
Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- at 
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task 
task) at 
Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__76.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- at 
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at 
Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e) at 
Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean 
ignoreUIThreadCheck) at Microsoft.VisualStudio.Services.VsTask.GetResult()

**Comment by cezarypiatek** [comment]
HI @MalcolmEllis 

Thanks for reporting this issue. I've been testing so far on 16.9.4. It looks like I need to upgrade the VS to verify that. I will take a look at this today later. Which version of MappingGenerator are you using?

**Comment by cezarypiatek** [comment]
I'm not able to reproduce the issue on VS 16.10 (might be caused by other extensions) but I applied a small fix that could potentially solve the problem. Please try updating MappingGenerator to v2021.6.19
