### ISSUE TITLE
Rider 2022 not supported

### ISSUE THREAD

**Issue by cezarypiatek** [cezarypiatek/MappingGeneratorIssueTracker#14]
I'm investigating this issue. Something changed in code refactoring loading architecture.

**Comment by sid-6581** [comment]
Any progress on this? I'm trying to evaluate MappingGenerator for Rider 2022, but I've only been able to get a couple of things to work.

**Comment by cezarypiatek** [comment]
Still working on this.  Today I've got a confirmation from JetBrains that they changed how roslyn extension libraries are loaded into the process.  I need to re-design how premium features are loaded. I hope I will be able to deliver the solution within 2 weeks.

**Comment by cezarypiatek** [comment]
@sid-6581 please try v2022.8.47. I've tested it on Rider 2021.3 and Rider 2022.2.

**Comment by samuel-mr** [comment]
@cezarypiatek do you have any plan to implement the Rider extension in the marketplace (instead of package)?

**Comment by cezarypiatek** [comment]
MappingGenerator relays on Roslyn SDK rather than Rider SDK so it's impossible to provide it as a "native" Rider extension.  The only way is through the NuGet package.

This nuget can be installed globally - more details on that here https://docs.mappinggenerator.net/basics/installation/#rider

**Comment by sid-6581** [comment]
> @sid-6581 please try v2022.8.47. I've tested it on Rider 2021.3 and Rider 2022.2.

Seems to work so far! I'll give it a shot. I can bring up the dialogs now, and the couple of things I've tried seem to work.

**Comment by cezarypiatek** [comment]
@sid-6581 thanks for the confirmation
