### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by kellyethridge** [cezarypiatek/MappingGeneratorIssueTracker#15]
Hello,

In Visual Studio 2022 I'm getting a NullReferenceException. The stack trace is:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at async MappingGenerator.Features.Refactorings.InvocationCleanup.InvocationCleanUpRefactoring.ComputeRefactoringsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

I'm assuming the MappingGenerator extension is the one having the issue based on the stack trace. Unfortunately more information is not given.

This only started recently, so maybe something with the latest release. I though maybe it didn't like my source code for some reason, however, it happens even on a new project (.NET 4.8 Console App) without adding any additional code.

Thank you.

**Comment by cezarypiatek** [comment]
Hi,

Thanks for reporting this issue. This should be addressed by the latest release https://github.com/cezarypiatek/MappingGeneratorReleases/releases/tag/2022.9.49

Please let me know if that problem disappeared after installing that update.

Kind regards,
Cezar

**Comment by kellyethridge** [comment]
OK, the update seems to have resolved the issue 👍 

Thank you!
Kelly
