### ISSUE TITLE
Nullable values mapping is mapped with throwing of exception

### ISSUE THREAD

**Issue by olesjo** [cezarypiatek/MappingGeneratorIssueTracker#16]
Hi,
I would like to have the option not to throw exception in the mapping when a nullable field is the source and the destination field is not. I.eks

It seesm like the "fallback to default value" does not do any differenct to "throw exception" in General Tab.

![issue](https://user-images.githubusercontent.com/17745364/196241366-2de4a19f-5c7c-4970-ba91-b8067a48bceb.PNG)

**Comment by cezarypiatek** [comment]
Hi @olesjo ,

Thanks for reporting this issue. Can you tell what are the types of properties that are incorrectly handled?

**Comment by cezarypiatek** [comment]
Hi @olesjo 

I've released a new version with the requested feature. More details here https://github.com/cezarypiatek/MappingGeneratorReleases/releases/tag/2022.9.50

Please let me know if that fits your needs. Any feedback is welcome.
