### ISSUE TITLE
Not using preferred expression body style

### ISSUE THREAD

**Issue by ngoov** [cezarypiatek/MappingGeneratorIssueTracker#20]
I have my Rider code style set to prefer expression body style. MappingGenerator does not default to this and this is also not configurable in the custom settings.

![image](https://user-images.githubusercontent.com/7434048/222969863-6cbdcae1-ba86-4952-bc13-e2f69b3894dd.png)

Is it possible to either make this available in the settings or default to this if it is set as preferred.

**Comment by cezarypiatek** [comment]
Hi,

Thanks for reporting this issue. I cannot read Rider preferences, but I can add MappingGenerator-specific setting for that.

**Comment by cezarypiatek** [comment]
Should be available in the next version

![image](https://user-images.githubusercontent.com/7759991/222977035-9487007a-51d4-4d87-a4b3-72dc3e341445.png)

**Comment by ngoov** [comment]
That was fast, thanks!

**Comment by cezarypiatek** [comment]
Should be available by now in v2023.3.55 https://github.com/cezarypiatek/MappingGeneratorReleases/releases/tag/2023.3.55
