### ISSUE TITLE
Cursor remains as pointer haver usage

### ISSUE THREAD

**Issue by kellyethridge** [cezarypiatek/MappingGeneratorIssueTracker#4]
Hello,

Just purchased this and it works great!

I'm using VS2019 and after I generate mapping code, the cursor remains as the default arrow pointer. It no longer reverts to the text selector pointer while in the text editor. It doesn't prevent VS from functioning, it's just visual nuisance.

Thank you.

**Comment by cezarypiatek** [comment]
Hi @kellyethridge

Thanks for reporting this issue. I've never experienced that but I will check it and try to reproduce it. Can you tell me which specific version of VS2019 are you using?

**Comment by kellyethridge** [comment]
Hello,

Yes, I'm using version 16.11.4 currently.

**Comment by cezarypiatek** [comment]
Confirmed. Good catch, I've never noticed that. I've just released a fix as v2021.8.29
Would you mind updating the extension and letting me know if the issue is gone?
