### ISSUE TITLE
Only Pro Edition Feature Dialog should say which Features require Pro.

### ISSUE THREAD

**Issue by barrywimlett** [cezarypiatek/MappingGeneratorIssueTracker#5]
So I'm a brand new user, I've just written my first empty map method and used the context menu; its opened up the dialog for the first time none of the check boxes are checked and I hit OK, create mapping.

"This feature is only available in the Pro Version"

 I have never used this before its settings are on default, whats most annoying is **it doesn't say WHICH feauture(s) require the Pro Version, so I can find them and turn them off and try and again." 

The whole point of try-ware is being able to try it.

Maybe consider an indicator on the create mapping dialog that indicates which are Pro-features.

**Comment by cezarypiatek** [comment]
Hi @barrywimlett 

Thanks for your feedback - I think I need to improve the message about the non-premium limitation to avoid further confusion.

The whole MappingGenerator Configurator dialog is a premium feature.  If you don't have an active license, then it works in the preview mode - you can play with all the options, review the results in the code window but you can't use the generated code, even if you left anything as default.

You can find more detailed descriptions of all configuration options in the documentation here https://docs.mappinggenerator.net/mappings/ui-configurator/

If the default settings are good enough for you then you can generate mapping code with a free option  (the item without 🔥)

![image](https://user-images.githubusercontent.com/7759991/142718515-da9e187d-6f1b-4121-9766-b4a036660f6e.png)
